-- Create the reviews table
create table reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  visit_date date not null,
  rating integer not null,
  message text not null,
  photos text[] -- Stores array of public image URLs
);

-- Enable Row Level Security (RLS)
alter table reviews enable row level security;

-- Policy to allow everyone to view reviews
create policy "Public reviews are viewable by everyone." on reviews
  for select using (true);

-- Policy to allow anyone to insert a review (you might want to restrict this later)
create policy "Anyone can insert a review." on reviews
  for insert with check (true);

-- STORAGE BUCKET SETUP
-- You also need to create a public storage bucket named 'review-images' in the Supabase Dashboard.
